### ISSUE TITLE
two date changes on workshop proposals page

### ISSUE THREAD

**Issue by brunyuriy** [martinvelez/fse2016#11]
On http://www.cs.ucdavis.edu/fse2016/calls/workshop-proposals/
please change
"Workshops will be held on November 13, 14, 18, and 19." 
to
"Workshops will be held on November 13, 14, and 18."

and
"Camera ready date for workshop papers: September 9, 2016"
to
"Camera ready date for workshop papers: September 15, 2016"

**Comment by martinvelez** [comment]
Done.  Please confirm and let me know if there is anything wrong.
