### ISSUE TITLE
Update Camera Ready Dates

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#12]
Hi Martin, Mona,

Please change the camera-ready date for all tracks to September 15, 2016.

The only exception is the research track, which has July 31, 2016.

The artifacts track also has July 31, 2016 (since the extra page is appended to the main conference paper)

Thanks,
Tom

**Comment by martinvelez** [comment]
I updated the camera-ready deadlines in the following pages.

http://www.cs.ucdavis.edu/fse2016/calls/research-papers/
http://www.cs.ucdavis.edu/fse2016/calls/artifacts/
http://www.cs.ucdavis.edu/fse2016/calls/workshop-proposals/
http://www.cs.ucdavis.edu/fse2016/calls/visions-and-reflections/
http://www.cs.ucdavis.edu/fse2016/calls/industry-papers/
http://www.cs.ucdavis.edu/fse2016/calls/demos/
http://www.cs.ucdavis.edu/fse2016/calls/doctoral-symposium/
http://www.cs.ucdavis.edu/fse2016/calls/student-research-competition/

**Comment by martinvelez** [comment]
Never mind.  I put the wrong date.  Let me fix it.

**Comment by martinvelez** [comment]
July 31, 2016
http://www.cs.ucdavis.edu/fse2016/calls/research-papers/
http://www.cs.ucdavis.edu/fse2016/calls/artifacts/

September 15, 2016
http://www.cs.ucdavis.edu/fse2016/calls/workshop-proposals/
http://www.cs.ucdavis.edu/fse2016/calls/visions-and-reflections/
http://www.cs.ucdavis.edu/fse2016/calls/industry-papers/
http://www.cs.ucdavis.edu/fse2016/calls/demos/
http://www.cs.ucdavis.edu/fse2016/calls/doctoral-symposium/
http://www.cs.ucdavis.edu/fse2016/calls/student-research-competition/
