### ISSUE TITLE
Please update the quick links with the next round of submissions

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#13]
1. In the Quick Links, create links that directly point to the EasyChair submission sites (in the same style of "Submit a workshop proposal") for the tracks with June 15 deadlines

Submit to the Visions and Reflections track
Submit to the Industry track
Submit to the Demo track
Submit to the Doctoral Symposium
Submit to the Student Research Competition

After the links add "All deadlines June 15, 2016".
1. Remove the text for Workshop Proposals and Research Papers

**Comment by martinvelez** [comment]
Is https://easychair.org/conferences/?conf=fse2016 the correct link for the SRC?

**Comment by martinvelez** [comment]
I updated the Quick Links box.  Please take a look and confirm it is ok.  

The only doubt I have is about the SRC Submission site.

**Comment by tzimmermsr** [comment]
Thanks Martin!

I’ve asked the SRC chairs for link. They will send it soon. –Tom

**Comment by tzimmermsr** [comment]
Hi Martin,

The submission link for the Doctoral Symposium is missing. Please add.

Thanks,
Tom

**Comment by martinvelez** [comment]
Added the "Submit to Doctoral Symposium" link in Quick Links.

**Comment by tzimmermsr** [comment]
The EasyChair link for the SRC is  https://easychair.org/conferences/?conf=fse16src

Please update in (1) the Quick Links on the main page and (2) the SRC Call for Papers.

**Comment by tzimmermsr** [comment]
In the Quick Links, there should not be the extra 6 at the end

https://easychair.org/conferences/?conf=fse16src6
=> https://easychair.org/conferences/?conf=fse16src (no 6)

**Comment by martinvelez** [comment]
Fixed quick link and updated call page.
