### ISSUE TITLE
Update conference dates

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#17]
The conference now ends on November 18.

Please update in the (1) header of any FSE page and (2) on the Welcome page http://www.cs.ucdavis.edu/fse2016/ 

The 24th ACM SIGSOFT International Symposium on the Foundations of Software Engineering will be held in Seattle, WA, USA between November 13 and November 19, 2016.

=> ... November 18, 2016.

Thanks,
Tom

**Comment by martinvelez** [comment]
Updated.
