### ISSUE TITLE
Update workshop websites

### ISSUE THREAD

**Issue by brunyuriy** [martinvelez/fse2016#19]
On http://www.cs.ucdavis.edu/fse2016/workshops/
please update the following three workshops to point to their workshop websites:
Workshop on App Market Analytics: http://appmarketanalytics.github.io/

The Java Pathfinder Workshop: https://jpf.byu.edu/jpf-workshop-2016

The 7th Workshop on Automating Test Case Design, Selection, and Evaluation (A-TEST): www.a-test.org

**Comment by brunyuriy** [comment]
Reminder, @martinvelez, can we update this please?

**Comment by martinvelez** [comment]
I have added the links.  Please double check.
