### ISSUE TITLE
Indirect workshop links

### ISSUE THREAD

**Issue by brunyuriy** [martinvelez/fse2016#20]
A bunch of the workshops on http://www.cs.ucdavis.edu/fse2016/workshops/ link to their webpages via indirect outline links (likely because the URLs were copied and pasted from an email).  For example,  The 2nd International Workshop on Software Analytics (SWAN) should link to http://www.softwareanalytics.ca/swan16/
but instead links to
https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.softwareanalytics.ca%2fswan16%2fHome.html&data=01%7c01%7ckimh%40microsoft.com%7c68e753604b694038ca1308d36ea36248%7c72f988bf86f141af91ab2d7cd011db47%7c1&sdata=80%2b8Joh5%2fzbl6B1ajidjcAWaoa7wSf5wqnocVvi2qpw%3d

Please fix for all workshops.

**Comment by brunyuriy** [comment]
Reminder, @martinvelez, can we update this please?

**Comment by martinvelez** [comment]
On it.

**Comment by tzimmermsr** [comment]
The workshop page still has the safe links... Please reopen.

**Comment by martinvelez** [comment]
Fixed.

http://www.cs.ucdavis.edu/fse2016/workshops/

**Comment by tzimmermsr** [comment]
Thx!
