### ISSUE TITLE
Include program committee information on SRC page 

### ISSUE THREAD

**Issue by gustavoasoares** [martinvelez/fse2016#22]
Please add the following information at the end of the page http://www.cs.ucdavis.edu/fse2016/calls/student-research-competition/: 

**ACM Student Research Competition Committee**
- Baishakhi Ray, University of Virginia
- Denys Poshyvanyk, College of William and Mary
- Harry Xu, University of California at Irvine
- Kıvanç Muşlu, Microsoft
- Manu Sridharan, Samsung Research America
- Michael Ernst, University of Washington
- Milos Gligoric, University of Texas at Austin
- Na Meng, Virginia Tech
- Vu Le, Microsoft

Thanks,
Gustavo

**Comment by martinvelez** [comment]
Done.  Can you please double check?

**Comment by gustavoasoares** [comment]
Thanks!
