### ISSUE TITLE
Mobile FSE web-page

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#27]
Please optimize the FSE web-page layout for mobile devices. 
- The titles are too big and go into the page content.
- The search and social widgets come first, but they should be after the content. (If we have to switch to a different layout on the desktop web-page to get this fixed, that's OK.)

![20160601_212202000_ios](https://cloud.githubusercontent.com/assets/2583274/15726320/09248d3a-2805-11e6-9e75-956a8c2dbf2c.png)

**Comment by tzimmermsr** [comment]
I suggest that we just move the two sidebars two the right. That should put the content first:
| Main Content | Quick Links | Search + Social |

Also, the title color switched to pink. I like pink, but white fits better. :-)

**Comment by MonaRahimi** [comment]
I have moved the two sidebars to the right and changed the font color from pink to white. Please let me know if you think this looks fine now.

**Comment by tzimmermsr** [comment]
It looks good on desktop, but on mobile devices the search/social box still comes first. I’ve tested on multiple phones with different browsers. That’s so strange...

--Tom

**Comment by MonaRahimi** [comment]
Yes, I noticed that too. I am looking into it.

**Comment by MonaRahimi** [comment]
I have posted it on wordpress forum. I think the theme we are using is overriding the position for mobile app. The custom CCS does not override it for the phone :(
