### ISSUE TITLE
Add NSF as Diamond supporter

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#28]
Please add NSF as a Diamond supporter on (1) the Supporter page and (2) the web-page footer.

Use the following logo: http://www.nsf.gov/images/logos/nsf4.gif (copy the file to the FSE web-site to avoid dependencies on other servers)

Link to: http://www.nsf.gov 

Thanks!

**Comment by MonaRahimi** [comment]
Just did. Let me know if you want me to change anything.

**Comment by tzimmermsr** [comment]
Please check the image. It got scaled up to 249x249 during upload but it's actual size is 166x166.

Thanks,
Tom

**Comment by MonaRahimi** [comment]
I thought you may want it to be slightly bigger than Platinum group same as others. Do you want it the original size?

**Comment by tzimmermsr** [comment]
Yes, slightly bigger than the Platinum group would be great but the logo should also not be pixelated.

Can you try the TIF file (resize, and convert to GIF/JPG) http://www.nsf.gov/images/logos/nsf4.tif

(via http://www.nsf.gov/policies/logos.jsp)

Thanks,
Tom

**Comment by MonaRahimi** [comment]
Tom, I think it looks better now with the tif file. Let me know if you think it is fine.

Thanks

**Comment by tzimmermsr** [comment]
Looks fantastic! Thanks Mona!
