### ISSUE TITLE
Please add Cisco as Gold Sponsor

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#29]
Please add Cisco as a Gold supporter on (1) the Supporter page and (2) the web-page footer. Within level, please sort alphabetically. 

Use this logo.
![cisco_logo_rgb_screen_2color](https://cloud.githubusercontent.com/assets/2583274/16212574/93e709a0-36fd-11e6-8eb0-96e128095aee.png)

Link to: http://research.cisco.com/

**Comment by MonaRahimi** [comment]
Just did please let me know if it looks fine. Thanks Tom

**Comment by tzimmermsr** [comment]
Looks great! Thanks Mona.
