### ISSUE TITLE
Changed footer background color

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#3]
To a light gray.

Makes it easier to see the end of the main content.

**Comment by tzimmermsr** [comment]
I like the gray for the footer. Thanks Martin!

Should we keep the background of the Sponsor and Supporter boxes in white? Otherwise the logos look funny. Please check the SIGSOFT logo next to the ACM logo. It's currently not loading.

--Tom

**Comment by martinvelez** [comment]
The image is a link to http://sigsoft.org but their website appears to be down.  I link now to a local Wordpress file so it should not break anymore.

You are right.  It looks a bit weird.  I changed the background-color of the boxes back to white.

**Comment by tzimmermsr** [comment]
Thanks Martin!
