### ISSUE TITLE
Add keynote speaker: James Herbsleb

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#30]
Please add **James Herbsleb** as keynote speaker to http://www.cs.ucdavis.edu/fse2016/program/keynotes/

Title: Building a Theory of Coordination: Why and How

Bio: James Herbsleb is a Professor in the Institute for Software Research in the School of Computer Science at Carnegie Mellon University, where he serves as Director of the PhD program in Societal Computing. His research interests lie primarily in the intersection of software engineering, computer-supported cooperative work, and socio-technical systems, focusing on such areas as geographically distributed development teams and large-scale open source development. He holds a PhD in psychology, and an MS in computer science. His research has won several awards at ICSE, including the Most Influential Paper award in 2010, Honorable Mention for Most Influential Paper award in 2011, and ACM Distinguished Paper Award in 2011. Other awards include an ACM Distinguished Paper award for ESEM 2008 and a Best Paper Award for CSCW 2006.  He was recently awarded the SIGSOFT Outstanding Research Award in 2016, and previously the Alan Newell Award for Research Excellence in 2014. For no apparent reason, he also holds a Juris Doctor degree and is a member of the Michigan Bar Association. For about two decades, he has worked with assorted colleagues and minions to try to understand the complex and dynamic relationship between human collaboration and the software that humans design and use. On his optimistic days, he feels he has made a bit of progress.

Pic: http://herbsleb.org/web-images/Jim/Jim-hands-cr170.jpg

**Comment by MonaRahimi** [comment]
Done, please let me know if you think it looks fine.

**Comment by tzimmermsr** [comment]
Perfect. Thanks @MonaRahimi
