### ISSUE TITLE
Create a page for each track under the Program menu

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#33]
Mona and Martin: Please create for each track a page under the Program menu with the list of accepted papers. (Remember that the pages have to be added to the menu manually.) Once you’ve created the pages, please let Venkatesh know so that he can publicize in our social media channels.

--Tom

**Comment by martinvelez** [comment]
Industry Track

http://www.cs.ucdavis.edu/fse2016/program/industry-track/

**Comment by martinvelez** [comment]
Visions and Reflections Track

http://www.cs.ucdavis.edu/fse2016/program/visions-and-reflections-track/

**Comment by MonaRahimi** [comment]
Just added DS accepted papers 
http://www.cs.ucdavis.edu/fse2016/program/doctoral-symposium-track/

**Comment by MonaRahimi** [comment]
Added SRC accepted papers 
http://www.cs.ucdavis.edu/fse2016/program/student-research-competition/

**Comment by obaysal** [comment]
@martinvelez @MonaRahimi The list of accepted Artifacts papers can be found here: https://docs.google.com/spreadsheets/d/1Bqy3iPzpuXAYtiuj_EgZpaBsEWaGXLBlE_FMmyaoNS8/edit?pref=2&pli=1#gid=0.

**Comment by martinvelez** [comment]
Demo Track

http://www.cs.ucdavis.edu/fse2016/program/demo-track/

**Comment by martinvelez** [comment]
@obaysal How would you like us to publish this list?  I can think of several ways.  For example, we can publish a simple list sorted by Artifact Title.  We can display three lists divided by category.

Also, what columns do you want us to include?  I imagine Artifact Title, Authors, URL, and Decision.  Anything else?

**Comment by martinvelez** [comment]
@obaysal For now, I added just a simple list of <Authors, Artifact Title>.  Please let me know if you would like for me to change or add anything.

http://www.cs.ucdavis.edu/fse2016/program/artifacts-track/

**Comment by obaysal** [comment]
@martinvelez thank you! looks good to me!

**Comment by martinvelez** [comment]
Updated

> Hi Mona,
> 
> Could you please fix the name of one of the participants?
> 
> Minhui Quan -> Minghui Quan  
> 
> Thanks,
> Gustavo
