### ISSUE TITLE
Picture when posting on social media

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#37]
Hi Mona, Martin,

When I post FSE links to Facebook the Facebook or NSF sponsor logo show up as preview pictures.

There seems to be a way to set the preview picture:

http://stackoverflow.com/questions/6693499/how-can-i-set-a-website-image-that-will-show-as-preview-on-facebook

Please set it to the attached picture.

Thanks,
Tom

**Comment by martinvelez** [comment]
Martin Velez mvelez999@gmail.com  Fri, Oct 21, 2016 at 5:17 PM
To: engineeringweb@ucdavis.edu, Heidi Steiner Arnold hmsteiner@ucdavis.edu
Hello Heidi,

I want to set the image the gets displayed when sharing a link on Facebook (or other sites).  Apparently, I need to add a meta tag but I cannot figure out how to do it.  So far, what I have read suggests that I (you) need to install a plugin.  Can you help me with this?

Saludos,
Martin Velez
University of California, Davis
(209) 292-4439
mvelez999@gmail.com
http://martinvelez.github.io

**Comment by tzimmermsr** [comment]
Any updates on this? Thanks, Tom

**Comment by martinvelez** [comment]
## @tzimmermsr

Please send me the URL of the link you are trying to share. 

## -Heidi

**Comment by tzimmermsr** [comment]
I want to share http://www.cs.ucdavis.edu/fse2016/ on Facebook, Twitter, etc. (or any link under that directory) and not get the Facebook or NSF logos as image associated with the link.

StackOevrflow has instructions on how to set different pictures:

I can provide better images if needed.

--Tom

**Comment by tzimmermsr** [comment]
This got sent too quickly.

I want to share http://www.cs.ucdavis.edu/fse2016/ on Facebook, Twitter, etc. (or any link under that directory) and _not_ get the Facebook or NSF logos as image associated with the link.

StackOverflow has instructions on how to set different pictures:

http://stackoverflow.com/questions/6693499/how-can-i-set-a-website-image-that-will-show-as-preview-on-facebookhttps://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fstackoverflow.com%2Fquestions%2F6693499%2Fhow-can-i-set-a-website-image-that-will-show-as-preview-on-facebook&data=02%7C01%7Ctzimmer%40microsoft.com%7C4f0073148ea24a9df6db08d3fa0ee549%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636126914288039494&sdata=JqbNAMr07dmFzVP7yt7hYcqyauaOlmNXkaaAan%2FKlK0%3D&reserved=0
I can provide better images if needed.

--Tom

**Comment by martinvelez** [comment]
Thanks, Tom.  I wrote back to Heidi, our WordPress admin.  


![screenshot from 2016-10-27 16 37 01](https://cloud.githubusercontent.com/assets/397957/19789320/aa55fefa-9c63-11e6-81ba-b15635c57697.png)

**Comment by martinvelez** [comment]
Hi Tom,

Heidi activated the Yoast SEO plugin.  I set the og:image meta property.

I tested posting on Facebook and now the Facebook preview shows the image you wanted to show.  By the way, Facebook has a specific debugger for this type of problem (https://developers.facebook.com/tools/debug/og/object/).

![screenshot from 2016-10-28 13 18 50](https://cloud.githubusercontent.com/assets/397957/19821125/96d2d264-9d11-11e6-97e3-eb2b4304ea5d.png)

**Comment by tzimmermsr** [comment]
That’s awesome. Thanks Martin and Heidi.

Does the plug-in also allow you to set any clipping.

Ideally the FSE 2016 in the top of the image would not be cut off.

We could also just cut off a bit of the bottom of the picture to make it fit in Facebook.

Thanks,
Tom
