### ISSUE TITLE
Updating SRC webpage

### ISSUE THREAD

**Issue by crubiog** [martinvelez/fse2016#39]
Hi!

Could you please add the list of finalists to the SRC webpage <http://www.cs.ucdavis.edu/fse2016/program/student-research-competition/>. Thank you!

Undergraduate Category:
Martin Kellogg: Combining Bug Detection and Test Case Generation
Christopher Mackie: Preventing Signedness Errors in Numerical Computations in Java
Felipe Rodrigues Monteiro Sousa: Bounded Model Checking of State-Space Digital Systems

Graduate Category:
Titus Barik: How should static analysis tools explain anomalies to developers?
Xinrui Guo: SmartDebug: An Interactive Debug Assistant for Java
Sebastian Kappler: Finding and Breaking Test Dependencies to Speed up Test Execution
Calvin Loncaric: Cozy: Synthesizing Collection Data Structures
Spencer Pearson: Evaluation of Fault Localization Techniques

**Comment by martinvelez** [comment]
Added.

http://www.cs.ucdavis.edu/fse2016/program/student-research-competition/
