### ISSUE TITLE
Call for Papers: Artifacts Track

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#5]
Dear FSE 2016 Web Chairs,

We would appreciate if you could post Call for Papers: Artifacts Track to the FSE 2016 website.

We have attached the two files here (.pdf, .pages and .docx provided):

1) Call for Papers: Artifacts Track
2) Artifacts Tutorial (with a potential url as "http://www.cs.ucdavis.edu/fse2016/calls/artifacts/artifacts-tutorial.html"). If you change this url, please make sure you modify this link in the CFP.

Please add Artifacts Track submission deadline to the Important Dates on the website too.

If you have any questions, we'd be happy to answer them.

Thank you!

Best Regards,

Olga

**Comment by martinvelez** [comment]
[FSE2016_CFP_Artifacts.pdf](https://github.com/martinvelez/fse2016/files/107609/FSE2016_CFP_Artifacts.pdf)
[Artifacts_Tutorial-FSE2016.pdf](https://github.com/martinvelez/fse2016/files/107610/Artifacts_Tutorial-FSE2016.pdf)

**Comment by martinvelez** [comment]
Added.

**Comment by tzimmermsr** [comment]
Hi Martin,

Could you please remove the artifacts call for now. We are going to make a few changes before it can go live.

Thanks,
Tom

**Comment by obaysal** [comment]
Hi @tzimmermsr and @timm,

I have revised Artifacts CFP. Please review it before we publish it. 

Thanks!

Olga

[FSE2016_CFP_Artifacts-v1.pdf](https://github.com/martinvelez/fse2016/files/136281/FSE2016_CFP_Artifacts-v1.pdf)

**Comment by martinvelez** [comment]
1) Changed status from published to draft of pages:
Call for Artifacts
Artifacts Tutorial

2) Removed dates from sidebar widgets.

3) We'll wait for further instruction.

**Comment by martinvelez** [comment]
HI @tzimmermsr, 

Is there any news on when this can go live?

**Comment by tzimmermsr** [comment]
No news yet. I hope soon.

**Comment by obaysal** [comment]
Hi @martinvelez ,

Here is an updated CFP. It can go live now. Thanks!
[FSE2016_CFP_Artifacts-v3.pdf](https://github.com/martinvelez/fse2016/files/186032/FSE2016_CFP_Artifacts-v3.pdf)

**Comment by tzimmermsr** [comment]
Thanks Olga! @martinvelez, please put the call online.

**Comment by martinvelez** [comment]
1. I have put the call online.  
2. I assumed that you also wanted to the Artifacts Tutorial page online so I did.

Please double check.  If there are any mistakes, like spelling errors or broken links, please let me know.

**Comment by obaysal** [comment]
Thank you, @martinvelez , for putting the call up! I have checked it and everything seems to be Ok. 
One thing: could you please change the sentence "1. FSE16 artifacts track, add my account to the repository." under the How to Submit heading to "FSE16 artifacts track, add my account to the repository." (including the quotes).

Thanks!

**Comment by martinvelez** [comment]
@obaysal, you're welcome!

I added the quotes.

http://www.cs.ucdavis.edu/fse2016/calls/artifacts/

**Comment by tzimmermsr** [comment]
@martinvelez The “Artifacts Tutorial” shows up as the first item in the menu (left from “FSE 2016”). Please remove.

In the Calls menu, Artifacts Track is first, please move as the last item.

Thanks,
Tom

**Comment by tzimmermsr** [comment]
Fixed.

**Comment by obaysal** [comment]
Hi @martinvelez,

Could you please make the following corrections:

1) In Table under Evaluation: change "Diamond, Silver and Bronze" labels to "Diamond, Platinum, and Gold". 

2) On Calls page (http://www.cs.ucdavis.edu/fse2016/calls/): Size limit should be "1 page including all text, references, and figures". May be up to 2 pages - will confirm with Tom. 

@tzimmermsr Can we go up to 2 pages for Artifacts to be consistent with other tracks? I think PC co-chairs were Ok with this. Please confirm. 

Thank you!

Olga

**Comment by martinvelez** [comment]
@obaysal , Changed labels to "Diamond, Platinum, and Gold".

**Comment by obaysal** [comment]
Hi @martinvelez ,

Could you please add the following updates to the Artifacts Track page, under "How to Submit, and the Review Process". [We would like to clarify some points for the authors]

```
1. All authors of the accepted research papers will receive an invitation with the instructions on how to submit their artifacts (by June 10 via email). 
2. Write a pdf submissions using the FSE 2016 Formatting Instructions. This submission would include two (1+1) pages:
    - *First* page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria. This page will be used to evaluate your artifact. 
    - *Second* page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted. The description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures). 
```

[The rest of the bullets remain as is]

Thank you, Martin!

Olga

**Comment by timm** [comment]
Dear FSE Author,

This email is to invite you to submit to the FSE'16 Artifacts track. Submissions are due June 30.

Please note one small correction to the on-line information. Your submission must be  **one** pdf file containing the following  **two** pages: 
- _First_ page: Describe the artifact along the dimensions of the scorecard (i.e., Insightful, Useful, Usable). Refer to the Evaluation criteria (at http://www.cs.ucdavis.edu/fse2016/calls/artifacts/). This page will be used to evaluate your artifact. 
- _Second_ page: Describe the artifact and how one can use it (mention about any difficulties one might encounter in using the artifact, or its maturity relative to the content of the paper). This page will be used in the proceedings and you will append it to your research paper once the artifact is accepted. The description of the artifact for the proceedings must not exceed 1 page (including all text, references, and figures). 

After that, the steps to submit are as follows:
1. Write one pdf file as per the above using the  FSE 2016 Formatting Instructions. Make the name of that pdf “XXX_YYY.pdf”, where XXX is the last name of the corresponding author and YYY is some short name for the artifact.
2. Get a GitHub account and email that name to fse2016artifacts@easychair.org with the subject line:
   “FSE16 artifacts track, add my account to the repository.”
3. Our reply to you will point to a GitHub repository and a directory for submissions. Drag and drop your pdf onto that directory.
4. Create an issue in that repository whose title is the XXX_YYY. Do not add any text to the comment.
5. Review of the artifacts will be conducted in GitHub where reviewers’ feedback will be public.

We look forward to your submission.

Regards,
Olga Baysal,Tim Menzies
(co-chairs, FSE artifact track).

**Comment by tzimmermsr** [comment]
@martinvelez Please also update the submission deadline on the FSE web-page to June 30. 

http://www.cs.ucdavis.edu/fse2016/calls/

**Comment by obaysal** [comment]
@martinvelez When updating the submission deadline in the table (as mentioned by @tzimmermsr), please keep the following text for the last column "1+1 pages (including all text, references, and figures)" on http://www.cs.ucdavis.edu/fse2016/calls/. Thanks!

**Comment by martinvelez** [comment]
I updated: 

[http://www.cs.ucdavis.edu/fse2016/calls/artifacts/](http://www.cs.ucdavis.edu/fse2016/calls/artifacts/)
[http://www.cs.ucdavis.edu/fse2016/calls/](http://www.cs.ucdavis.edu/fse2016/calls/)

**Comment by obaysal** [comment]
Thank you, @martinvelez!

**Comment by obaysal** [comment]
@martinvelez Could you please double check http://www.cs.ucdavis.edu/fse2016/calls/ as it looks not updated to me. Thanks!

**Comment by obaysal** [comment]
@martinvelez thanks for updating all! looks good now!

**Comment by obaysal** [comment]
@martinvelez Sorry for bugging you a lot. Could you please update the Artifacts track page removing the phrase "References (may be in a second page)" under Goal and Scope. Thanks!

**Comment by MonaRahimi** [comment]
@obaysal done!

**Comment by obaysal** [comment]
Thank you @MonaRahimi!

**Comment by obaysal** [comment]
@MonaRahimi could you please update the "How to Submit" text for the Artifacts track CFP page as follows: "3. Write a pdf submissions using the FSE 2016 Formatting Instructions. Papers must not exceed 1 page (including all text, references, and figures). Make the name of that pdf “XXX_YYY.pdf”, where XXX is the last name of the corresponding author and YYY is some short name for the artifact." to be changed to "3. Make the name of that pdf “XXX_YYY.pdf”, where XXX is the last name of the corresponding author and YYY is some short name for the artifact."

Thanks!

**Comment by MonaRahimi** [comment]
@obaysal Could you please see if this looks fine to you. Thanks

**Comment by obaysal** [comment]
Perfect! Thanks @MonaRahimi!

**Comment by obaysal** [comment]
@MonaRahimi We'd appreciate if you could you please update Important Dates for the Artifacts track:
Author notification: July 29, 2016
Camera-ready deadline: August 08, 2016

**Comment by MonaRahimi** [comment]
Done!

**Comment by obaysal** [comment]
Looks good, thank you @MonaRahimi !
