### ISSUE TITLE
Add Facebook as Silver Supporter

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#6]
![facebook-06-2015-blue](https://cloud.githubusercontent.com/assets/397957/13133433/110f8b0a-d5b0-11e5-927b-df226e9c4238.png)

**Comment by tzimmermsr** [comment]
Can you please also add to http://www.cs.ucdavis.edu/fse2016/supporters/

**Comment by tzimmermsr** [comment]
And within a level, please sort alphabetically. Thanks!

--Tom

**Comment by martinvelez** [comment]
Added Facebook logo to supporters page in alphabetical order.
Reordered in alphabetical order in footer.
