### ISSUE TITLE
Create Program Menu

### ISSUE THREAD

**Issue by tzimmermsr** [martinvelez/fse2016#7]
Hi Martin, Mona,

Please create a "Program" menu (between "FSE 2016" and "Calls") with the following two pages for now:
1. Keynotes

(I will send information soon on our first keynote speaker.)
1. Showcase

<h1>FSE 2016 Showcase of the Best of Software Engineering Practice</h1>

To meet the always increasing demands for better and faster software produced by better and faster developers, practicing software engineers continually innovate and streamline the processes and tools that they use. This track will feature invited presentations by innovative software engineering practitioners.  The aim of the track is to promote a dialogue between those at the forefront of the best of software engineering practice and researchers focusing on changing the direction of software engineering.

The talks for the Showcase will be announced in Springer/Summer 2016.
## 

Thanks,
Tom

**Comment by tzimmermsr** [comment]
Any updates on the Program page for the Showcase?

Please move the "Program" menu between "FSE 2016" and "Calls".

**Comment by martinvelez** [comment]
1) Added page for Showcase.

2) Moved "Program" between "FSE 2016" and "Calls".  I did it by changing its page order from 2 to 1.

3) The program page is empty.  Should it contain something?

**Comment by tzimmermsr** [comment]
Thanks!

Regarding 3), How about we add a table to the Program page that shows the week overview? Similar to what ICSE has http://2016.icse.cs.txstate.edu/week-overview

Here are the contents for FSE table (we can add specific workshops later, once they've been accepted)

![image](https://cloud.githubusercontent.com/assets/2583274/13798821/0973f3ea-ead7-11e5-9d47-e97670fb080f.png)

As the program emerges, we can add links to the individual pages. Now, we only link to Keynotes and Showcase.

Thoughts?

**Comment by martinvelez** [comment]
Sounds good to me.  I added the table to the Program page.  

I am closing this issue since the original task has been performed.

**Comment by tzimmermsr** [comment]
Thanks Martin! That’s great.

It looks like the Doctoral Symposium goes the entire week (as it has an entire row) but it is only on Tuesday.

Maybe add vertical lines or do something with colors?

--Tom
