### ISSUE TITLE
Call for Student Research Competition papers 

### ISSUE THREAD

**Issue by gustavoasoares** [martinvelez/fse2016#8]
Dear FSE 2016 Web Chairs,

We would appreciate if you could post Call for Student Research Competition to the FSE 2016 website. The content of the page is in the following google docs:

 https://docs.google.com/a/computacao.ufcg.edu.br/document/d/10o0TaydBZAfTLbJXdYijcjMLIq0MGEEm9vHkXoKuAhs/edit?usp=sharing 

If you have any questions, we'd be happy to answer them.

Thank you!
Best Regards,
Gustavo and Cindy

**Comment by tzimmermsr** [comment]
One change request:

Consider applying as a student volunteer. SIGSOFT, NSF and Google will provide student travel support through the CAPS program.
=>
Consider applying as a student volunteer. SIGSOFT will provide student travel support through the CAPS program.

Correct the CAPS link to http://www.sigsoft.org/resources/caps.html [without the extra slash)

**Comment by gustavoasoares** [comment]
Thanks, Tom! Fixed!

**Comment by tzimmermsr** [comment]
@martinvelez, Mona: Any updates on when the call will be online?

**Comment by martinvelez** [comment]
The content has been added.  

[http://www.cs.ucdavis.edu/fse2016/calls/student-research-competition/](http://www.cs.ucdavis.edu/fse2016/calls/student-research-competition/)

**Comment by tzimmermsr** [comment]
Thanks @martinvelez !

**Comment by tzimmermsr** [comment]
Quick note. I've added the general submission polices to the SRC web-page (under Requirements). The change is already live, no more action is needed.

I added the general submission policies to the SRC page.

<b>Important:</b> Note that the official publication date is the date the proceedings are made available in the ACM Digital Library. This date may be up to two weeks prior to the first day of FSE 2016. The official publication date affects the deadline for any patent filings related to published work.

At least one author of each accepted paper must register and present the paper at FSE 2016 in order for the paper to be published in the proceedings. One-day registrations do NOT satisfy the registration requirement. Please carefully read the complete list of <a href="http://www.cs.ucdavis.edu/fse2016/calls/#policies">FSE Submission Policies and Policies for Accepted Contributions</a>.

**Comment by tzimmermsr** [comment]
@martinvelez Under Sponsor on the SRC web-page, please add the Microsoft Research logo. 

You can copy the image from here: http://esec-fse15.dei.polimi.it/images/MSRLogoBlack.jpg 

(Please copy the logo so that we have all logos on the FSE server)
