### ISSUE TITLE
Program Table

### ISSUE THREAD

**Issue by martinvelez** [martinvelez/fse2016#9]
Added a border to cells by adding custom CSS.
# program tr, th, td {

border: 1px solid #000000;
}

@tzimmermsr: Is the Doctoral Symposium on Monday or Tuesday?

**Comment by tzimmermsr** [comment]
The doctoral symposium is Tuesday.

**Comment by tzimmermsr** [comment]
Sorry, got confused with ICSE

The doctoral symposium is Monday = the day before the main FSE conference.

Thanks Martin!
